jenkins:
  securityRealm:      
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        name: ${JENKINS_ADMIN_ID}
        password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/stable/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
  nodeMonitors:
    - clock: {}
    - responseTime: {}

globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"

appearance:
  themeManager:
    disableUserThemes: true
    theme: "dark"

tool:
  git:
    installations:
    - home: "git"
      name: "git"
  go:
    installations:
      - name: "go-1.24.6"
        home: "/usr/local/go"