jenkins:
  securityRealm:      
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: admin
        name: admin
        password: admin
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
  nodeMonitors:
    - clockMonitor: {}
    - responseTimeMonitor: {}

globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"

appearance:
  themeManager:
    disableUserThemes: true
    theme: "dark"

tool:
  git:
    installations:
    - home: "git"
      name: "git"
  go:
    installations:
    - name: "go-1.24.6"
      properties:
      - installSource:
          installers:
          - golangInstaller:
              id: "1.24.6"