apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
spec:
  ports:
    - name: http-metrics
      port: {{ .Values.service.port }}
      targetPort: http-metrics
  selector:
    app: kube-state-metrics
