image:
  repository: custom-jenkins
  tag: custom
  pullPolicy: IfNotPresent

serviceAccount:
  name: jenkins

allowedNamespaces:
  - dev
  - prod
  
service:
  type: NodePort
  port: 30000
  targetPort: 8080
  nodePort: 30000

persistence:
  enabled: true
  storageClass: "standard"
  size: 2Gi

resources: {}
